### ISSUE TITLE
编译不了？

### ISSUE THREAD

**Issue by 70kg** [imishx/ActivityRouter#1]
Error:Could not GET 'http:/xxx/nexus/content/groups/public/com/github/imishx/activityrouter/annotation/1.0/annotation-1.0.pom'. Received status code 503 from server: Service Unavailable
<a href="toggle.offline.mode">Enable Gradle 'offline mode' and sync project</a>

请问什么原因？

似乎maven地址有问题，依赖本地lib可以了。

**Comment by 70kg** [comment]
前段时间我也写了一个类似的 `Router` 的东西http://70kg.github.io/2016/11/16/Router%E8%AE%BE%E8%AE%A1/  有时间也要试试apt这个东西，确实方便很多

**Comment by 70kg** [comment]
大兄弟，有点巧啊 https://github.com/70kg/70kg.github.io/issues/2

**Comment by 70kg** [comment]
大概看了一下，简单说一下我的看法，可能不对，见谅：

1.  `InterceptorChain` 类似一个manager的东西，管理所有的 `Interceptor`，那么它是否有足够的合理性去实现 `Interceptor` 这个接口。而且使用了类似递归去调用所有的 `Interceptor` ，可否使用循环，更简单易懂。

2. `Interceptor` 接口实现是否不够清晰合理。似乎一个 `Interceptor` 实现必须要手动去调用 `interceptorChain.doIntercept(context, url, interceptorChain);`才能继续下去，如果我是第三方使用者，很难去想起来去调用这个方法。是否有改进的余地。

3. 当从路由表中获取的`OpenTask` 为空，直接返回，表现类似点击没反应，是否应该加个容错处理，允许去自定义错误处理方式，而不是简单粗暴的返回。

4. `Router` 和 `Routers` 的命名是否可以更易懂一些。

**Comment by imishx** [comment]
首先感谢关注，这个东西网上实现已经很多了，思路大同小异，也借鉴了很多优秀的想法，开源出来希望可以和大家共同讨论研究，关于你的看法我做一些说明：
1、InterceptorChain是模仿的java ee的 FilterChain，做过java web的应该比较了解。主要考虑的是对拦截之后的行为的抽象。
2、容错部分其实还没做，后续会加上。
3、命名却是有点不好。。。
